{
 "title": "Plant Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Sensor_0x10", "label": "Sensor_0x10", "query": "Cactus" },
   { "name": "Sensor_0x11", "label": "Sensor_0x11", "query": "Palm Tree" },
   { "name": "Sensor_0x12", "label": "Sensor_0x12", "query": "Avocado Tree" },
   { "name": "Sensor_0x13", "label": "Sensor_0x13", "query": "Rose" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(`insertTime`) AS `time`,\r\n  `sensor_links`.`plantName` AS `metric`,\r\n  `sensor_data`.`T` as `value` \r\nFROM `sensor_data`\r\nLEFT JOIN `sensor_links` ON\r\n`sensor_data`.`address` = `sensor_links`.`sensorAddress`\r\nWHERE $__timeFilter(`insertTime`)"
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(`insertTime`) AS `time`,\r\n  `sensor_links`.`plantName` AS metric,\r\n  (4095-`sensor_data`.`M`) AS `value`\r\nFROM `sensor_data`\r\nLEFT JOIN `sensor_links` ON\r\n`sensor_data`.`address` = `sensor_links`.`sensorAddress`\r\nWHERE $__timeFilter(`insertTime`)"
    }
   ]
  },
  {
   "title": "Ambient Light",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(`insertTime`) AS `time`,\r\n  `sensor_links`.`plantName` AS metric,\r\n  (4095-`sensor_data`.`A`) AS `value`\r\nFROM `sensor_data`\r\nLEFT JOIN `sensor_links` ON\r\n`sensor_data`.`address` = `sensor_links`.`sensorAddress`\r\nWHERE $__timeFilter(`insertTime`)"
    }
   ]
  },
  {
   "title": "Watering data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "mlitre" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(`timestamp`) AS `time`,\r\n  `sensor_links`.`plantName` AS metric,\r\n  `waterVolume` AS `value`\r\nFROM `watering_data`\r\nLEFT JOIN `sensor_links` ON\r\n`watering_data`.`solenoidAddress` = `sensor_links`.`solenoidAddress`\r\nWHERE $__timeFilter(`timestamp`)"
    }
   ]
  }
 ]
}